
language: node_js
node_js:
  - '12'
  - '14'
before_install:
  - npm i yarn -g
install:
  - yarn
script:
  - yarn workspace doggy-nav-server cov
after_script:
  - yarn workspace doggy-nav-server clean
