environment:
  matrix:
    - nodejs_version: '12'
    - nodejs_version: '12'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm i yarn && node_modules\.bin\yarn

test_script:
  - node --version
  - yarn --version
  - yarn run test

build: off
