FROM node:22-alpine
LABEL name="marvelous"

RUN mkdir -p /app
COPY ./packages/doggy-nav-server/package.json /app/package.json
COPY yarn.lock /app/yarn.lock
RUN cd /app && yarn install --production
ADD ./packages/doggy-nav-server/dist/. /app

WORKDIR /app

EXPOSE 3002
ENV PORT=3002
# ENTRYPOINT [ "/bin/sh" ]
# CMD [ "-c", "while true;do echo 1;sleep 120s;done"]
CMD [ "/usr/local/bin/yarn", "docker-start" ]