FROM node:14-alpine
LABEL name="marvelous"

COPY ./packages/doggy-nav-server/package.json /tmp/package.json
COPY yarn.lock /tmp/yarn.lock
RUN cd /tmp && yarn install
RUN mkdir -p /app && cp -a /tmp/node_modules /app/

WORKDIR /app
ADD ./packages/doggy-nav-server/. ./
RUN yarn build

EXPOSE 3002
ENV PORT=3002
# ENTRYPOINT [ "/bin/sh" ]
# CMD [ "-c", "while true;do echo 1;sleep 120s;done"]
CMD [ "/usr/local/bin/yarn", "docker-start" ]