FROM node:14-alpine as build
LABEL name="marvelous"

COPY ./packages/doggy-nav-admin/package.json /tmp/package.json
COPY yarn.lock /tmp/yarn.lock
RUN cd /tmp && yarn
RUN mkdir -p /app && cp -a /tmp/node_modules /app/

WORKDIR /app
ADD ./packages/doggy-nav-admin/. ./

RUN yarn build

FROM nginx:1.21-alpine
ARG nginxCfg=nginx-admin.conf
COPY --from=build /app/dist /usr/local/share/nginx/html/dist

COPY ./deploy/$nginxCfg /etc/nginx/$nginxCfg
# RUN chmod +r /etc/nginx/$nginxCfg
# RUN chmod -R 777 /usr/local/share/nginx/html \
#     && chmod -R 777 /usr/local/share/nginx/html/dist
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 8080
ENTRYPOINT [ "sh","-c" ]
CMD ["envsubst '$DOGGY_SERVER' < /etc/nginx/nginx-admin.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
# CMD ["sh", "-c", "echo $DOGGY_SERVER && while true;do echo 1;sleep 120s;done"]
