packages:
  - packages/*

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  axios@<0.30.0: '>=0.30.0'
  axios@<0.30.2: '>=0.30.2'
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  dompurify@<3.2.4: '>=3.2.4'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@<2.5.4: '>=2.5.4'
  immer@>=7.0.0 <9.0.6: '>=9.0.6'
  jsonwebtoken@<9.0.0: '>=9.0.0'
  jsonwebtoken@<=8.5.1: '>=9.0.0'
  koa@>=2.16.2 <2.16.3: '>=2.16.3'
  micromatch@<4.0.8: '>=4.0.8'
  mongoose@<6.13.5: '>=6.13.5'
  mongoose@<6.13.6: '>=6.13.6'
  node-fetch@<2.6.7: '>=2.6.7'
  passport@<0.6.0: '>=0.6.0'
  path-to-regexp@>=0.2.0 <1.9.0: '>=1.9.0'
  postcss@<8.4.31: '>=8.4.31'
  send@<0.19.0: '>=0.19.0'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  validator@<13.15.20: '>=13.15.20'
  vite@<4.5.10: '>=4.5.10'
  vite@<4.5.11: '>=4.5.11'
  vite@<4.5.12: '>=4.5.12'
  vite@<4.5.13: '>=4.5.13'
  vite@<=4.5.13: '>=4.5.14'
  vite@<=4.5.5: '>=4.5.6'
  vite@<=5.4.19: '>=5.4.20'
  vite@>=4.0.0 <4.5.4: '>=4.5.4'
  vite@>=4.0.0 <=4.5.2: '>=4.5.3'
  vite@>=4.0.0 <=4.5.3: '>=4.5.4'
