version: '3.3'
services:
  doggy-server:
    container_name: doggyserver
    image: doggyserver
    build:
      context: ./../.
      dockerfile: "Dockerfile-Server"
    restart: always
    environment:
      - MONGO_URL=mongodb:27017
    ports:
      - 3002:3002
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb-container
    image: mongo:3
    restart: always
    volumes:
      - ./logs/data:/data/db
    ports:
      - "27117:27017"
      - "27118:27018"