import type {
  GroupService,
  CategoryService,
  NavService,
  FavoriteService,
  FavoriteCommandService,
  FavoriteFolderService,
  InviteCodeService,
  TagService,
  TranslateService,
  UserService,
  UserAuthService,
  RoleService,
  EmailSettingsService,
  ApplicationService,
  NavAdminService,
  Token,
  AfficheService,
} from 'doggy-nav-core';

export const TOKENS = {
  GroupService: Symbol('GroupService') as Token<GroupService>,
  CategoryService: Symbol('CategoryService') as Token<CategoryService>,
  NavService: Symbol('NavService') as Token<NavService>,
  FavoriteService: Symbol('FavoriteService') as Token<FavoriteService>,
  FavoriteCommandService: Symbol('FavoriteCommandService') as Token<FavoriteCommandService>,
  FavoriteFolderService: Symbol('FavoriteFolderService') as Token<FavoriteFolderService>,
  InviteCodeService: Symbol('InviteCodeService') as Token<InviteCodeService>,
  TagService: Symbol('TagService') as Token<TagService>,
  TranslateService: Symbol('TranslateService') as Token<TranslateService>,
  UserService: Symbol('UserService') as Token<UserService>,
  AuthService: Symbol('AuthService') as Token<UserAuthService>,
  RoleService: Symbol('RoleService') as Token<RoleService>,
  EmailSettingsService: Symbol('EmailSettingsService') as Token<EmailSettingsService>,
  ApplicationService: Symbol('ApplicationService') as Token<ApplicationService>,
  NavAdminService: Symbol('NavAdminService') as Token<NavAdminService>,
  PromptService: Symbol('PromptService') as Token<any>,
  AfficheService: Symbol('AfficheService') as Token<AfficheService>,
  UserRepo: Symbol('UserRepo') as Token<any>,
  RoleRepo: Symbol('RoleRepo') as Token<any>,
  CategoryRepo: Symbol('CategoryRepo') as Token<any>,
  NavRepo: Symbol('NavRepo') as Token<any>,
  GroupRepo: Symbol('GroupRepo') as Token<any>,
  TagRepo: Symbol('TagRepo') as Token<any>,
};
