'use strict';

module.exports = {
  write: true,
  plugin: 'autod-egg',
  prefix: '^',
  devprefix: '^',
  exclude: [
    'test/fixtures',
    'coverage',
    'dist',
    'typings',
    'app/public',
    'node_modules',
  ],
  dep: [
    // egg core/runtime
    'egg',
    'egg-scripts',
    'egg-mongoose',
    'egg-jwt',
    'egg-passport',
    'egg-cors',
    'egg-security',
    'egg-ratelimiter',
    // libs used at runtime
    'mongoose',
    'jsonwebtoken',
    'passport',
    'passport-github2',
    'passport-google-oauth20',
    'passport-oauth2',
    'dotenv',
    'axios',
    'cheerio',
    'node-cron',
    'request',
    'tslib',
  ],
  devdep: [
    'autod',
    'autod-egg',
    'egg-bin',
    'egg-ts-helper',
    'typescript',
    'ts-node',
    'eslint',
    '@typescript-eslint/parser',
    '@typescript-eslint/eslint-plugin',
    'esbuild',
    'egg-ci',
  ],
  keep: [],
  semver: {},
  test: 'scripts',
};
